services:
  - type: web
    name: my-web-service
    env: node
    plan: free
    region: frankfurt
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
databases:
  - name: db
    postgresMajorVersion: '18'
    plan: basic-256mb
    region: frankfurt